version: "3.7"

services:
  order:
    ports:
      - "8080:8080"

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

